pool:
  name: Default

steps:
- script: |
    java -version
    echo $JAVA_HOME
  displayName: "Check Java"

- script: mvn -version
  displayName: "Check Maven"

- script: mvn clean package
  displayName: "Build Maven Project"
