pool:
  name: Default

steps:
- script: java -version
  displayName: "Check Java"

- script: mvn -version
  displayName: "Check Maven"

- script: mvn clean package
  displayName: "Build Maven Project"
