trigger:
- master

pool:
  name: Default
  demands:
  - Agent.Name -equals cdlabvm

steps:
- script: |
    java -version
    echo $JAVA_HOME
  displayName: "Verify Java Version"

- script: mvn clean package -DskipTests=true
  displayName: "Build Maven Project"
